# Only tests on macOS. Other tests are done at GitLab.
# While issue #12 is open the tests will fail for Guile.

env:
  matrix:
    - SCHEME="ChezScheme_master"
    #- SCHEME="Guile_2.2"
    #- SCHEME="Larceny"
    #- SCHEME="Racket_HEAD"
    #- SCHEME="SagittariusScheme"
    #- SCHEME="VicareScheme"

matrix:
  allow_failures:
    - env: SCHEME="Larceny"
    - env: SCHEME="Racket_HEAD"
    - env: SCHEME="SagittariusScheme"
    - env: SCHEME="VicareScheme"

sudo: false
dist: trusty

addons:
  apt:
    packages:
      # Larceny
      - libc6:i386
      # Sagittarius and GNU Guile
      - libgc-dev
      # GNU Guile
      - libunistring-dev

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  #- linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar xz; fi

before_script:
  # Install scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(INSTALL_TARGET=$HOME/opt scheme-ci-master/install-scheme.sh $SCHEME)"
  - rm -rf build-*/*/
  - source .akku/bin/activate
  - mkdir -p ~/.local/share/akku/keys.d
  - cp akku-archive-*.gpg ~/.local/share/akku/keys.d

script:
  - bin/akku.sps update
  - bin/akku.sps install
  - if [[ $SCHEME = chezscheme ]]; then private/build.chezscheme.sps </dev/null; fi
  - ./run-tests.sh
